### ISSUE TITLE
Use basic code intel while language server hasn't returned a result

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph-typescript#107]
While packages are still installing, we could show the basic-code-intel result if the language server couldn't find one (not just if no server is configured).
For hover and references we can replace the content/list once the real result is in.
For definition, we can always use a small timeout after which code intel is used.

@chrismwendt wdyt?

**Comment by chrismwendt** [comment]
(continuing from https://github.com/sourcegraph/sourcegraph-typescript/pull/140/files#r270624520)

Complaints were filed against the `race()` behavior in https://sourcegraph.slack.com/archives/C07KZF47K/p1553879931025500, so I reverted it in https://github.com/sourcegraph/sourcegraph-go/pull/58

I might implement progressive-refinement behavior and put it behind a feature flag to gather feedback https://github.com/sourcegraph/sourcegraph-go/pull/57#issuecomment-478156715, but it might be met with complaints similar to the `race()` behavior. I'm curious if you're optimistic about it.

**Comment by chrismwendt** [comment]
Closing because:

- Falling back reduces confidence in code intelligence for people who expect the language server's results https://sourcegraph.slack.com/archives/C07KZF47K/p1553879931025500
- Falling back would make it more difficult to troubleshoot language server setup issues such as https://sourcegraph.slack.com/archives/C0W2E592M/p1554110783001800
